/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package trip.pojo;

public class ClosestAirport {
	private java.lang.String lng;

 	public void setLng(java.lang.String lng) {
		this.lng = lng;
	}

	public java.lang.String getLng() {
		return lng;
	}

	private java.lang.String lat;

 	public void setLat(java.lang.String lat) {
		this.lat = lat;
	}

	public java.lang.String getLat() {
		return lat;
	}

	private java.lang.String iata;

 	public void setIata(java.lang.String iata) {
		this.iata = iata;
	}

	public java.lang.String getIata() {
		return iata;
	}

}