/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package trip.pojo;

public class DestinationAirport {
	private Double lng;

 	public void setLng(Double lng) {
		this.lng = lng;
	}

	public Double getLng() {
		return lng;
	}

	private Double lat;

 	public void setLat(Double lat) {
		this.lat = lat;
	}

	public Double getLat() {
		return lat;
	}

	private String iata;

 	public void setIata(String iata) {
		this.iata = iata;
	}

	public String getIata() {
		return iata;
	}

}