/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package trip.pojo;

public class Entrada {
	private ClosestAirport closestAirport;

 	public void setClosestAirport(ClosestAirport closestairport) {
		this.closestAirport = closestairport;
	}

	public ClosestAirport getClosestAirport() {
		return closestAirport;
	}

	private java.lang.String endDate;

 	public void setEndDate(java.lang.String enddate) {
		this.endDate = enddate;
	}

	public java.lang.String getEndDate() {
		return endDate;
	}

	private OriginAirport originAirport;

 	public void setOriginAirport(OriginAirport originairport) {
		this.originAirport = originairport;
	}

	public OriginAirport getOriginAirport() {
		return originAirport;
	}

	private DestinationAirport destinationAirport;

 	public void setDestinationAirport(DestinationAirport destinationairport) {
		this.destinationAirport = destinationairport;
	}

	public DestinationAirport getDestinationAirport() {
		return destinationAirport;
	}

	private StepoverElement[] stepovers;

 	public void setStepovers(StepoverElement[] stepovers) {
		this.stepovers = stepovers;
	}

	public StepoverElement[] getStepovers() {
		return stepovers;
	}

	private java.lang.String paxes;

 	public void setPaxes(java.lang.String paxes) {
		this.paxes = paxes;
	}

	public java.lang.String getPaxes() {
		return paxes;
	}

	private java.lang.String startDate;

 	public void setStartDate(java.lang.String startdate) {
		this.startDate = startdate;
	}

	public java.lang.String getStartDate() {
		return startDate;
	}

}