/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package trip.pojo;

public class StepoverElement {
	private Double lng;

 	public void setLng(Double lng) {
		this.lng = lng;
	}

	public Double getLng() {
		return lng;
	}

	private Double lat;

 	public void setLat(Double lat) {
		this.lat = lat;
	}

	public Double getLat() {
		return lat;
	}

	private String address;

 	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddress() {
		return address;
	}

}